[env]
PROBE_RS_CHIP = "STM32F105RC"

# LOG: trace, debug, info, warn, error
DEFMT_LOG                        = "trace"
DEFMT_RTT_BUFFER_SIZE            = "1024"
EMBASSY_EXECUTOR_TASK_ARENA_SIZE = "1024"


[build]
target = "thumbv7m-none-eabi"
rustflags = [
    "-Clinker-plugin-lto",
    "-Clink-arg=-Tlink.x",
    "-Clink-arg=--nmagic",
    "-Clink-arg=-Tdefmt.x",
    # "-Cforce-frame-pointers",
    # "-Zmacro-backtrace",
]
