[env]
CARGO_REGISTRY_DEFAULT = "rsproxy"
PROBE_RS_PROTOCOL      = "swd"


[alias]
rr = "r -r"
br = "b -r"
x  = "rr --"


[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# linker = "rust-lld"
runner = [
    "probe-rs",
    "run",
    "--preverify",
    "--no-location",
    # "--verify",
    # "--connect-under-reset",
    # "--log-format", "{L} {s}",
]
