[env]
PROBE_RS_CHIP = "STM32F401RC"

CARGO_REGISTRY_DEFAULT = "rsproxy"
PROBE_RS_PROTOCOL      = "swd"

# LOG: trace, debug, info, warn, error
DEFMT_LOG                        = "trace"
DEFMT_RTT_BUFFER_SIZE            = "1024"
EMBASSY_EXECUTOR_TASK_ARENA_SIZE = "1024"


[alias]
rr = "run --release"
br = "build --release"


[build]
target = "thumbv7em-none-eabihf"
rustflags = [
    "-Clinker-plugin-lto",
    "-Clink-arg=-Tlink.x",
    "-Clink-arg=--nmagic",
    "-Clink-arg=-Tdefmt.x",
    # "-Cforce-frame-pointers",
    # "-Zmacro-backtrace",
]


[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# linker = "rust-lld"
runner = [
    "probe-rs",
    "run",
    "--preverify",
    "--no-location",
    # "--verify",
    # "--connect-under-reset",
    # "--log-format", "{L} {s}",
]
